apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: aws-provider-test
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
      - action:
          - "secretsmanager:GetSecretValue"
          - "secretsmanager:DescribeSecret"
        effect: Allow
        resource: "arn:aws:secretsmanager:eu-north-1:800216399102:secret:Mysecretname-WqIVmD"
  secretRef:
    name: aws-creds
    namespace: dev
  serviceAccountNames:
    - default